import React, { useId } from 'react';

/**
 * AccessibleSvg
 * -------------
 * Wrapper around <svg> that gives a concept diagram a programmatically
 * determinable accessible name (WCAG 1.1.1 Non-text Content, Level A).
 *
 * It applies role="img" plus an <svg><title>/<desc> pair wired via
 * aria-labelledby / aria-describedby using stable, collision-free ids
 * generated by React's useId(). The <title> is the short accessible name
 * (announced by screen readers); the optional <desc> carries a longer
 * explanation of what the diagram conveys.
 *
 * Usage:
 *   <AccessibleSvg
 *     viewBox="0 0 500 160"
 *     className="w-full h-full"
 *     title="Operant conditioning loop"
 *     desc="A stimulus leads to a behavior, which is followed by a consequence that feeds back to alter future behavior."
 *   >
 *     ...svg children...
 *   </AccessibleSvg>
 *
 * Notes:
 *  - `title` is required so every diagram has a non-empty accessible name.
 *  - If `desc` is omitted, only the <title>/aria-labelledby wiring is applied.
 *  - Any extra props (viewBox, className, style, etc.) pass through to <svg>.
 */
export const AccessibleSvg = ({ title, desc, children, ...svgProps }) => {
    const reactId = useId();
    const titleId = `asvg-title-${reactId}`;
    const descId = `asvg-desc-${reactId}`;

    return (
        <svg
            role="img"
            aria-labelledby={desc ? `${titleId} ${descId}` : titleId}
            {...svgProps}
        >
            <title id={titleId}>{title}</title>
            {desc ? <desc id={descId}>{desc}</desc> : null}
            {children}
        </svg>
    );
};

export default AccessibleSvg;
