// Parity check: run the ported TS policy over the fixtures and assert the
// output is IDENTICAL to the Python golden file (generated by gen_golden.py).
//
// Deno is not assumed to be installed. policy.ts is transpiled to a temporary
// ESM module (the bundle step is done by run_parity.sh via esbuild) and
// imported here. This harness then deep-compares each decision.
//
// Usage (driven by run_parity.sh):
//   node run_parity.mjs <policy_js_path> <golden_json_path> <fixtures_json_path>

import { readFileSync } from "node:fs";
import { pathToFileURL } from "node:url";

const [, , policyPath, goldenPath, fixturesPath] = process.argv;
if (!policyPath || !goldenPath || !fixturesPath) {
  console.error(
    "usage: node run_parity.mjs <policy_js> <golden_json> <fixtures_json>",
  );
  process.exit(2);
}

const policy = await import(pathToFileURL(policyPath).href);
const golden = JSON.parse(readFileSync(goldenPath, "utf-8"));
const fixtures = JSON.parse(readFileSync(fixturesPath, "utf-8"));

const goldenByName = new Map(golden.map((g) => [g.name, g.decision]));

// Canonical JSON for deep, order-insensitive object comparison (arrays keep
// order; object keys are sorted).
function canon(value) {
  if (Array.isArray(value)) {
    return "[" + value.map(canon).join(",") + "]";
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return "{" + keys.map((k) => JSON.stringify(k) + ":" + canon(value[k])).join(",") + "}";
  }
  if (typeof value === "number") {
    // Normalize -0 and keep full precision.
    return JSON.stringify(Object.is(value, -0) ? 0 : value);
  }
  return JSON.stringify(value);
}

let pass = 0;
const failures = [];

for (const fx of fixtures) {
  const expected = goldenByName.get(fx.name);
  if (!expected) {
    failures.push({ name: fx.name, reason: "no golden record" });
    continue;
  }
  const actual = policy.select_support_move(
    { ...fx.features },
    fx.annotation_adaptive ?? true,
    fx.prefer_advance ?? false,
  );

  // Compare the load-bearing fields explicitly + the whole decision.
  const fields = [
    "policy_mode",
    "candidate_actions",
    "action_scores",
    "selected_action",
    "rejected_actions",
    "reason_codes",
    "evidence_snapshot",
  ];
  const diffs = [];
  for (const f of fields) {
    if (canon(actual[f]) !== canon(expected[f])) {
      diffs.push({
        field: f,
        ts: actual[f],
        py: expected[f],
      });
    }
  }
  if (diffs.length === 0) {
    pass += 1;
  } else {
    failures.push({ name: fx.name, diffs });
  }
}

console.log("=".repeat(60));
console.log("PYTHON <-> TS PARITY CHECK");
console.log("=".repeat(60));
console.log(`fixtures: ${fixtures.length}`);
console.log(`PASS:     ${pass}`);
console.log(`FAIL:     ${failures.length}`);
for (const fx of fixtures) {
  const ok = !failures.find((f) => f.name === fx.name);
  console.log(`  [${ok ? "PASS" : "FAIL"}] ${fx.name}`);
}
if (failures.length > 0) {
  console.log("\nFAILURE DETAIL:");
  console.log(JSON.stringify(failures, null, 2));
  process.exit(1);
}
console.log("\nALL FIXTURES MATCH: TS policy == Python policy.");
process.exit(0);
