#!/usr/bin/env node
/** Generate the frontend course-count manifest from the canonical MDX corpus. */
import { mkdir, readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const contentRoot = path.join(root, 'frontend', 'content')
const outputPath = path.join(root, 'frontend', 'src', 'generated', 'contentManifest.js')

const courseEntries = await readdir(contentRoot, { withFileTypes: true })
const manifest = {}

for (const courseEntry of courseEntries) {
  if (!courseEntry.isDirectory() || courseEntry.name.startsWith('_')) continue
  const coursePath = path.join(contentRoot, courseEntry.name)
  const chapterEntries = await readdir(coursePath, { withFileTypes: true })
  let chapterCount = 0
  let sectionCount = 0
  for (const chapterEntry of chapterEntries) {
    if (!chapterEntry.isDirectory()) continue
    const chapterPath = path.join(coursePath, chapterEntry.name)
    const chapterStat = await stat(chapterPath)
    if (!chapterStat.isDirectory()) continue
    const sectionFiles = (await readdir(chapterPath)).filter((name) => name.endsWith('.mdx'))
    if (!sectionFiles.length) continue
    chapterCount += 1
    sectionCount += sectionFiles.length
  }
  manifest[courseEntry.name] = { chapters: chapterCount, sections: sectionCount }
}

const source = `// Generated by scripts/generate_content_manifest.mjs. Do not edit manually.\n`+
  `export const CONTENT_COUNTS = ${JSON.stringify(manifest, null, 2)}\n`
await mkdir(path.dirname(outputPath), { recursive: true })
await writeFile(outputPath, source, 'utf8')
console.log(`Generated ${outputPath} for ${Object.keys(manifest).length} courses.`)
