// Parity check for the Cloudflare Worker policy port.
//
// Transpiles the Worker's src/policy.ts (verbatim copy of the parity-verified
// Supabase policy.ts) to ESM via the frontend's bundled esbuild, runs it over
// the SAME fixtures the Supabase port uses, and deep-compares every field to the
// Python golden file (generated by the existing supabase gen_golden.py). MUST be
// N/N IDENTICAL, proving CF policy == Python.
//
// Usage:
//   node parity/run_parity.mjs
//
// It locates everything relative to this file, so it can be run from anywhere.

import { readFileSync, existsSync, rmSync } from "node:fs";
import { pathToFileURL } from "node:url";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = dirname(fileURLToPath(import.meta.url));
const CF_FUNC_DIR = resolve(HERE, "..");
const REPO_ROOT = resolve(CF_FUNC_DIR, "..", "..");
const POLICY_TS = join(CF_FUNC_DIR, "src", "policy.ts");
const GOLDEN = join(HERE, "golden.json");
const FIXTURES = join(HERE, "fixtures.json");
const TMP_JS = join(HERE, ".policy.bundle.mjs");

function findEsbuild() {
  const base = join(REPO_ROOT, "frontend", "node_modules", ".bin");
  const candidates = [
    join(base, "esbuild"),
    join(base, "esbuild.cmd"),
    join(base, "esbuild.CMD"),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

const esbuild = findEsbuild();
if (!esbuild) {
  console.error(
    "esbuild not found under frontend/node_modules/.bin. Run `npm install` in frontend/ first.",
  );
  process.exit(3);
}

// Transpile + bundle policy.ts to a single ESM file (resolves the .ts import
// extension and strips types).
const build = spawnSync(esbuild, [
  POLICY_TS,
  "--bundle",
  "--format=esm",
  "--platform=node",
  `--outfile=${TMP_JS}`,
], { stdio: "inherit", shell: process.platform === "win32" });

if (build.status !== 0) {
  console.error("esbuild failed to transpile policy.ts");
  process.exit(build.status ?? 4);
}

const policy = await import(pathToFileURL(TMP_JS).href);
const golden = JSON.parse(readFileSync(GOLDEN, "utf-8"));
const fixtures = JSON.parse(readFileSync(FIXTURES, "utf-8"));

const goldenByName = new Map(golden.map((g) => [g.name, g.decision]));

// Canonical JSON for deep, order-insensitive object comparison (arrays keep
// order; object keys are sorted).
function canon(value) {
  if (Array.isArray(value)) {
    return "[" + value.map(canon).join(",") + "]";
  }
  if (value && typeof value === "object") {
    const keys = Object.keys(value).sort();
    return "{" +
      keys.map((k) => JSON.stringify(k) + ":" + canon(value[k])).join(",") + "}";
  }
  if (typeof value === "number") {
    return JSON.stringify(Object.is(value, -0) ? 0 : value);
  }
  return JSON.stringify(value);
}

let pass = 0;
const failures = [];

for (const fx of fixtures) {
  const expected = goldenByName.get(fx.name);
  if (!expected) {
    failures.push({ name: fx.name, reason: "no golden record" });
    continue;
  }
  const actual = policy.select_support_move(
    { ...fx.features },
    fx.annotation_adaptive ?? true,
    fx.prefer_advance ?? false,
  );

  const fields = [
    "policy_mode",
    "candidate_actions",
    "action_scores",
    "selected_action",
    "rejected_actions",
    "reason_codes",
    "evidence_snapshot",
  ];
  const diffs = [];
  for (const f of fields) {
    if (canon(actual[f]) !== canon(expected[f])) {
      diffs.push({ field: f, cf: actual[f], py: expected[f] });
    }
  }
  if (diffs.length === 0) pass += 1;
  else failures.push({ name: fx.name, diffs });
}

try {
  rmSync(TMP_JS, { force: true });
} catch (_) { /* ignore */ }

console.log("=".repeat(60));
console.log("PYTHON <-> CLOUDFLARE WORKER POLICY PARITY CHECK");
console.log("=".repeat(60));
console.log(`fixtures: ${fixtures.length}`);
console.log(`PASS:     ${pass}`);
console.log(`FAIL:     ${failures.length}`);
for (const fx of fixtures) {
  const ok = !failures.find((f) => f.name === fx.name);
  console.log(`  [${ok ? "PASS" : "FAIL"}] ${fx.name}`);
}
if (failures.length > 0) {
  console.log("\nFAILURE DETAIL:");
  console.log(JSON.stringify(failures, null, 2));
  process.exit(1);
}
console.log("\nALL FIXTURES MATCH: Cloudflare Worker policy == Python policy.");
process.exit(0);
