export const ARTIFACT_TAXONOMY = [
    {
        id: 'storyboard_sequence',
        family: 'Instructional Design Artifact',
        terms: ['storyboard', 'frame', 'narration', 'signaling', 'slide'],
        definition: 'A sequenced learning design artifact that shows what learners see, do, and decide across frames or screens.',
        submissionForms: ['frame sequence', 'slide storyboard', 'screen-by-screen lesson plan', 'narration and learner-action table'],
        nonExamples: ['a paragraph saying the lesson is engaging', 'AI-generated slides with no learner action or evidence link'],
        qualitySignal: 'Visible before/after frame-level revision tied to a learning principle or accessibility constraint.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['storyboard.(pptx|pdf|png)', 'revision-trace.md'],
            acceptedFormats: ['.pptx', '.pdf', '.png', '.md', '.docx'],
            namingPattern: 'COURSE_SECTION_storyboard_v##',
            requiredSections: ['frame id', 'screen or slide content', 'narration', 'learner action', 'design principle', 'accessibility note', 'before/after change'],
            minimumContent: 'At least 3 ordered frames with one explicit revision linked to a learning or accessibility constraint.',
        },
    },
    {
        id: 'cognitive_load_diagnosis',
        family: 'Learning Analysis Artifact',
        terms: ['cognitive load', 'intrinsic', 'extraneous', 'germane', 'diagnosis'],
        definition: 'A diagnosis table that identifies learning demands, unnecessary load, and support for schema construction in a concrete lesson or interface.',
        submissionForms: ['load diagnosis table', 'principle-to-problem matrix', 'before/after load analysis'],
        nonExamples: ['a generic list of Mayer principles', 'a polished visual with no diagnosis or revision decision'],
        qualitySignal: 'The revision separates intrinsic, extraneous, and germane load and names the evidence for the change.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['load-diagnosis.(md|docx|xlsx|pdf)', 'revision-trace.md'],
            acceptedFormats: ['.md', '.docx', '.xlsx', '.csv', '.pdf'],
            namingPattern: 'COURSE_SECTION_load-diagnosis_v##',
            requiredSections: ['task or segment', 'intrinsic load', 'extraneous load', 'germane support', 'evidence source', 'revision decision'],
            minimumContent: 'At least 4 diagnosed segments with one rejected AI suggestion and one implemented load-reduction revision.',
        },
    },
    {
        id: 'traceability_matrix',
        family: 'Prototype Evidence Artifact',
        terms: ['prototype', 'readme', 'traceability', 'repository', 'ai-use'],
        definition: 'A trace linking theory, design decisions, AI/tool use, and concrete prototype or repository changes.',
        submissionForms: ['README traceability matrix', 'prototype change log', 'AI-use disclosure with design rationale'],
        nonExamples: ['a final prototype screenshot only', 'a vague statement that AI helped improve the design'],
        qualitySignal: 'Each visible change is tied to a theory, rubric, test observation, or AI-use boundary.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['traceability-matrix.(md|csv)', 'AI-USE.md', 'prototype-snapshot.(png|pdf|url)'],
            acceptedFormats: ['.md', '.csv', '.pdf', '.png', '.url'],
            namingPattern: 'COURSE_SECTION_traceability_v##',
            requiredSections: ['feature or screen', 'theory or rubric evidence', 'AI/tool use', 'accepted change', 'rejected change', 'known limitation'],
            minimumContent: 'At least 5 trace rows, including one visible prototype change and one AI-use boundary.',
        },
    },
    {
        id: 'policy_judgment_map',
        family: 'Ethical Judgment Artifact',
        terms: ['policy', 'privacy', 'ethobot', 'teachgen', 'tension', 'equity', 'consent'],
        definition: 'A map or memo that makes a classroom technology value conflict visible and defends a bounded implementation decision.',
        submissionForms: ['design tension map', 'AI policy memo', 'transcript annotation with decision boundary', 'stakeholder risk matrix'],
        nonExamples: ['a generic pro/con list', 'a policy copied from AI without classroom constraints'],
        qualitySignal: 'The revision names a stakeholder tension, evidence source, rejected risk, and implementation boundary.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['policy-map.(md|docx|pdf)', 'evidence-annotation.(md|csv|pdf)'],
            acceptedFormats: ['.md', '.docx', '.pdf', '.csv'],
            namingPattern: 'COURSE_SECTION_policy-map_v##',
            requiredSections: ['stakeholders', 'value tension', 'evidence source', 'accepted recommendation', 'rejected risk', 'boundary condition'],
            minimumContent: 'At least 2 stakeholders, 1 concrete value tension, and 1 bounded implementation decision.',
        },
    },
    {
        id: 'data_story',
        family: 'Data/Spreadsheet Artifact',
        terms: ['excel', 'spreadsheet', 'chart', 'pivot', 'data story', 'table'],
        definition: 'A data artifact that turns a spreadsheet or chart into a defensible claim with units, grouping, source, and limitation.',
        submissionForms: ['claim-first chart', 'spreadsheet analysis memo', 'pivot-table interpretation', 'data story slide'],
        nonExamples: ['a chart with no claim', 'a spreadsheet screenshot with no interpretation or limitation'],
        qualitySignal: 'The revision improves claim-evidence alignment without distorting units, grouping, or uncertainty.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['data-workbook.(xlsx|csv)', 'data-story.(md|pdf|pptx)'],
            acceptedFormats: ['.xlsx', '.csv', '.md', '.pdf', '.pptx', '.png'],
            namingPattern: 'COURSE_SECTION_data-story_v##',
            requiredSections: ['claim-first title', 'data source', 'unit', 'grouping', 'chart or table', 'limitation'],
            minimumContent: 'At least 1 chart or pivot table, 1 source note, 1 unit statement, and 1 limitation.',
        },
    },
    {
        id: 'career_evidence_packet',
        family: 'Professional Evidence Artifact',
        terms: ['resume', 'portfolio', 'github pages', 'career', 'evidence packet'],
        definition: 'A career-facing artifact that makes a skill claim verifiable through specific evidence rather than broad self-description.',
        submissionForms: ['resume bullet with evidence', 'portfolio evidence map', 'GitHub Pages project rationale', 'role-specific skill claim'],
        nonExamples: ['a generic resume bullet', 'an AI-polished profile that overclaims expertise'],
        qualitySignal: 'The revision narrows the claim, names evidence, and removes unsupported overclaiming.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['career-artifact.(pdf|docx|md)', 'evidence-map.md'],
            acceptedFormats: ['.pdf', '.docx', '.md', '.url'],
            namingPattern: 'COURSE_SECTION_career-evidence_v##',
            requiredSections: ['role target', 'skill claim', 'evidence artifact', 'accepted wording', 'removed overclaim', 'next verification step'],
            minimumContent: 'At least 3 skill claims, each tied to a specific file, link, project, or course evidence item.',
        },
    },
    {
        id: 'usability_revision_protocol',
        family: 'Evaluation Artifact',
        terms: ['usability', 'observation', 'test script', 'feedback', 'iteration'],
        definition: 'A protocol or observation-to-revision trace that turns usability evidence into a prioritized artifact change.',
        submissionForms: ['moderated test script', 'observation-to-revision memo', 'iteration priority table', 'usability evidence board'],
        nonExamples: ['a satisfaction comment only', 'a list of changes with no observation or rationale'],
        qualitySignal: 'The revision links an observed issue to a prioritized change and notes what evidence remains missing.',
        submissionSpec: {
            version: 'artifact-submission-spec-v1',
            requiredFiles: ['usability-protocol.(md|docx|pdf)', 'observation-table.(csv|xlsx|md)'],
            acceptedFormats: ['.md', '.docx', '.pdf', '.csv', '.xlsx'],
            namingPattern: 'COURSE_SECTION_usability-revision_v##',
            requiredSections: ['task scenario', 'participant profile', 'observed issue', 'severity', 'revision decision', 'remaining evidence gap'],
            minimumContent: 'At least 2 observations with severity ratings and one prioritized revision decision.',
        },
    },
]

export const DEFAULT_ARTIFACT_DEFINITION = {
    id: 'general_work_product',
    family: 'Course Work Product',
    definition: 'A concrete course deliverable that can be inspected, critiqued, revised, and defended with evidence.',
    submissionForms: ['draft artifact', 'before/after revision trace', 'evidence-backed work product'],
    nonExamples: ['a generic reflection with no inspectable product', 'a final answer with no revision trail'],
    qualitySignal: 'The learner can show what changed, why it changed, what evidence supported it, and what limitation remains.',
    submissionSpec: {
        version: 'artifact-submission-spec-v1',
        requiredFiles: ['artifact.(md|docx|pdf|pptx|xlsx|csv|png)', 'revision-trace.md'],
        acceptedFormats: ['.md', '.docx', '.pdf', '.pptx', '.xlsx', '.csv', '.png'],
        namingPattern: 'COURSE_SECTION_artifact-type_v##',
        requiredSections: ['artifact claim', 'evidence source', 'accepted suggestion', 'rejected or modified suggestion', 'revised state', 'transfer constraint'],
        minimumContent: 'One inspectable artifact plus a revision trace showing what changed, why, what was rejected, and what limitation remains.',
    },
}

export function getArtifactDefinition(artifact = '') {
    const normalized = String(artifact || '').toLowerCase()
    return ARTIFACT_TAXONOMY.find((entry) =>
        entry.terms.some((term) => normalized.includes(term))
    ) || DEFAULT_ARTIFACT_DEFINITION
}
