const VISUALS = [
    { gradient: 'linear-gradient(135deg,#0f5167 0%,#c8e2ec 55%,#f7f3ea 100%)', accent: '#0f5167', motif: 'lab bench' },
    { gradient: 'linear-gradient(135deg,#243b53 0%,#81a4cd 52%,#f4f7fb 100%)', accent: '#243b53', motif: 'field test' },
    { gradient: 'linear-gradient(135deg,#3f5f45 0%,#b8d7b2 54%,#fbf8ee 100%)', accent: '#3f5f45', motif: 'material sample' },
    { gradient: 'linear-gradient(135deg,#5c3b6f 0%,#d2b7e5 55%,#fff8ee 100%)', accent: '#5c3b6f', motif: 'design studio' },
    { gradient: 'linear-gradient(135deg,#6f4e37 0%,#e4c8a0 55%,#fffaf0 100%)', accent: '#6f4e37', motif: 'site review' },
    { gradient: 'linear-gradient(135deg,#7a1f3d 0%,#f2b6c8 55%,#fff7f7 100%)', accent: '#7a1f3d', motif: 'policy room' },
    { gradient: 'linear-gradient(135deg,#164e63 0%,#67e8f9 54%,#f0fdfa 100%)', accent: '#164e63', motif: 'control panel' },
    { gradient: 'linear-gradient(135deg,#4a5568 0%,#cbd5e0 48%,#f7fafc 100%)', accent: '#4a5568', motif: 'evidence board' },
    { gradient: 'linear-gradient(135deg,#365314 0%,#bef264 50%,#f7fee7 100%)', accent: '#365314', motif: 'prototype wall' },
    { gradient: 'linear-gradient(135deg,#1e3a8a 0%,#93c5fd 55%,#eff6ff 100%)', accent: '#1e3a8a', motif: 'flight path' },
    { gradient: 'linear-gradient(135deg,#713f12 0%,#facc15 48%,#fefce8 100%)', accent: '#713f12', motif: 'risk matrix' },
    { gradient: 'linear-gradient(135deg,#3b0764 0%,#c084fc 52%,#faf5ff 100%)', accent: '#3b0764', motif: 'online seminar' },
    { gradient: 'linear-gradient(135deg,#064e3b 0%,#6ee7b7 54%,#ecfdf5 100%)', accent: '#064e3b', motif: 'usability test' },
    { gradient: 'linear-gradient(135deg,#7c2d12 0%,#fdba74 52%,#fff7ed 100%)', accent: '#7c2d12', motif: 'warehouse floor' },
    { gradient: 'linear-gradient(135deg,#312e81 0%,#a5b4fc 55%,#eef2ff 100%)', accent: '#312e81', motif: 'AI audit' },
    { gradient: 'linear-gradient(135deg,#134e4a 0%,#5eead4 50%,#f0fdfa 100%)', accent: '#134e4a', motif: 'sensor map' },
    { gradient: 'linear-gradient(135deg,#581c87 0%,#f0abfc 52%,#fdf4ff 100%)', accent: '#581c87', motif: 'storyboard' },
    { gradient: 'linear-gradient(135deg,#1f2937 0%,#9ca3af 52%,#f9fafb 100%)', accent: '#1f2937', motif: 'structural sketch' },
    { gradient: 'linear-gradient(135deg,#14532d 0%,#86efac 55%,#f0fdf4 100%)', accent: '#14532d', motif: 'swarm grid' },
    { gradient: 'linear-gradient(135deg,#083344 0%,#7dd3fc 52%,#f0f9ff 100%)', accent: '#083344', motif: 'navigation trace' },
]

const SCENARIOS = [
    {
        id: 'needs-analysis-brakes',
        tags: ['needs', 'analysis', 'compliance', 'warehouse', 'instructional design', 'safety'],
        setting: 'A warehouse has rising forklift incidents, and leadership wants a five-hour compliance video by Friday.',
        learnerRole: 'You are the instructional designer asked to approve the solution.',
        friction: 'The request names training as the fix before the team has checked whether the workplace system is broken.',
        decisionPoint: 'What evidence would you gather before agreeing to build the course?',
        variables: ['Maintenance logs', 'Incident timing', 'Supervisor observation notes', 'Existing certification records'],
        choices: [
            { label: 'Build now', action: 'Produce the requested video immediately.', tradeoff: 'Fast delivery, weak diagnosis.', feedback: 'Useful only if the problem is knowledge recall; risky if brakes or workflow are the cause.' },
            { label: 'Audit first', action: 'Run a rapid front-end analysis before design.', tradeoff: 'Slower start, stronger fit.', feedback: 'Best first move because it separates skill gaps from environmental constraints.' },
            { label: 'Add quiz', action: 'Keep the video but add a post-test.', tradeoff: 'Measures recall, not field behavior.', feedback: 'A quiz cannot reveal whether the forklift, policy, or floor layout is causing incidents.' },
        ],
        successCriteria: ['Cause is named before intervention', 'Evidence connects to the claimed performance gap', 'Recommendation distinguishes training from non-training fixes'],
        theoryMoves: ['Needs analysis begins with performance conditions, not content requests.', 'Instructional design is defensible when the solution follows the cause.', 'Assessment should measure the target behavior, not only recall.'],
        reflectionPrompt: 'Which piece of evidence would most quickly disconfirm the training request?',
    },
    {
        id: 'cognitive-load-prototype',
        tags: ['cognitive load', 'interface', 'prototype', 'ail606', 'screen', 'usability'],
        setting: 'A prototype lesson has dense tooltips, three sidebars, and a simulation that starts before learners know the goal.',
        learnerRole: 'You are reviewing the screen before the next usability test.',
        friction: 'Useful resources are present, but they compete for attention at the exact moment learners need orientation.',
        decisionPoint: 'Which part of the screen should be revised first?',
        variables: ['Number of simultaneous cues', 'Learner goal clarity', 'Extraneous navigation steps', 'Time to first correct action'],
        choices: [
            { label: 'Hide extras', action: 'Collapse secondary explanations until the learner requests them.', tradeoff: 'Less visible support, lower clutter.', feedback: 'Strong move when optional help is increasing extraneous load.' },
            { label: 'Add more labels', action: 'Explain every control with more on-screen text.', tradeoff: 'Clearer names, heavier reading burden.', feedback: 'May help vocabulary but can worsen split attention.' },
            { label: 'Auto-play demo', action: 'Show the full simulation before the task.', tradeoff: 'Engaging preview, passive start.', feedback: 'Risky unless the demo is tightly signaled and followed by action.' },
        ],
        successCriteria: ['Primary action is visible within five seconds', 'Optional support does not block task progress', 'Learners can state the goal before manipulating controls'],
        theoryMoves: ['Extraneous load comes from unnecessary processing demands.', 'Signaling directs attention toward the relevant relation.', 'Germane work increases when learners can act on the concept.'],
        reflectionPrompt: 'What should disappear from the first view so the core task becomes easier?',
    },
    {
        id: 'gecko-adhesion-robot',
        tags: ['gecko', 'adhesion', 'robot', 'surface', 'bio-inspired', 'materials'],
        setting: 'A turbine-inspection robot must grip curved blades, release cleanly, and leave no residue on protective coatings.',
        learnerRole: 'You are choosing the adhesion strategy for the prototype.',
        friction: 'High grip is not enough; the robot also needs controllable detachment and durability under repeated cycles.',
        decisionPoint: 'Which test would best reveal whether gecko-inspired adhesion is appropriate?',
        variables: ['Surface roughness', 'Peel angle', 'Dust contamination', 'Cycle count', 'Required shear force'],
        choices: [
            { label: 'Max grip', action: 'Optimize only for highest pull-off force.', tradeoff: 'Strong hold, poor release evidence.', feedback: 'Incomplete because directional adhesion depends on both attachment and detachment.' },
            { label: 'Cycle test', action: 'Measure grip and release over repeated contaminated surfaces.', tradeoff: 'More work, stronger deployment evidence.', feedback: 'Best move because it tests the actual use condition.' },
            { label: 'Use glue', action: 'Switch to a permanent adhesive patch.', tradeoff: 'Simple bond, residue risk.', feedback: 'Conflicts with the requirement to detach without damaging coatings.' },
        ],
        successCriteria: ['Grip is measured in the loading direction', 'Release force stays low enough for motion', 'Performance survives contamination and repetition'],
        theoryMoves: ['Biological inspiration must be abstracted into a functional mechanism.', 'Directional adhesion changes with geometry and loading path.', 'Engineering transfer depends on constraints, not resemblance alone.'],
        reflectionPrompt: 'What condition would make the biological analogy fail in deployment?',
    },
    {
        id: 'quiet-drone-serration',
        tags: ['drone', 'noise', 'owl', 'serration', 'aeroacoustics', 'bio-inspired'],
        setting: 'A delivery drone passes safety tests but residents complain about a sharp evening buzz near apartment balconies.',
        learnerRole: 'You are deciding whether owl-inspired edge serrations belong in the next rotor prototype.',
        friction: 'The design may reduce noise but could also reduce lift efficiency or complicate manufacturing.',
        decisionPoint: 'What should the first prototype compare?',
        variables: ['Blade tip speed', 'Frequency profile', 'Lift-to-power ratio', 'Manufacturing tolerance'],
        choices: [
            { label: 'Change shape', action: 'Add serrations and compare sound spectra at matched lift.', tradeoff: 'Direct evidence, controlled test effort.', feedback: 'Best because noise reduction must be judged at equivalent performance.' },
            { label: 'Slow rotors', action: 'Lower rotor speed without changing blade geometry.', tradeoff: 'Simple, possible payload loss.', feedback: 'Useful baseline, but it does not test the bio-inspired mechanism.' },
            { label: 'Survey users', action: 'Ask residents whether the drone sounds better.', tradeoff: 'Human relevance, weak causal evidence.', feedback: 'Good later, but first isolate the acoustic mechanism.' },
        ],
        successCriteria: ['Noise is compared at equal lift', 'Frequency shifts are measured, not guessed', 'Energy cost remains acceptable'],
        theoryMoves: ['A bio-inspired feature must preserve the target function.', 'A fair test controls the performance variable.', 'Perception matters, but mechanism testing comes first.'],
        reflectionPrompt: 'Which metric would keep the team from celebrating a quieter but weaker drone?',
    },
    {
        id: 'ethics-emotion-detection',
        tags: ['ai ethics', 'privacy', 'education', 'consent', 'emotion', 'school'],
        setting: 'A district is offered free webcam emotion detection that flags students who appear inattentive.',
        learnerRole: 'You are preparing the pre-deployment ethics review.',
        friction: 'The tool promises engagement data but collects sensitive signals from students under institutional pressure.',
        decisionPoint: 'Which concern should stop the pilot until redesigned?',
        variables: ['Student consent', 'Data retention', 'False attention labels', 'Teacher action after alerts'],
        choices: [
            { label: 'Pilot quietly', action: 'Test with one classroom before notifying families.', tradeoff: 'Fast evidence, weak legitimacy.', feedback: 'Not defensible because sensitive monitoring requires clear notice and limits.' },
            { label: 'Limit data', action: 'Reject video inference and use opt-in learning artifacts instead.', tradeoff: 'Less biometric data, more pedagogical validity.', feedback: 'Strong move because it aligns evidence with learning rather than surveillance.' },
            { label: 'Trust vendor', action: 'Accept the vendor FERPA claim as enough.', tradeoff: 'Low workload, high governance risk.', feedback: 'Legal alignment is not the same as ethical necessity or proportionality.' },
        ],
        successCriteria: ['Data minimization is explicit', 'Students are not coerced into biometric monitoring', 'Teacher decisions are not driven by opaque affect labels'],
        theoryMoves: ['Privacy review asks whether collection is necessary, not only permitted.', 'Consent is weak when participation is mandatory.', 'Educational AI should support learning evidence, not infer inner states casually.'],
        reflectionPrompt: 'What lower-risk evidence could answer the same instructional question?',
    },
    {
        id: 'learning-objectives-abcd',
        tags: ['objectives', 'bloom', 'abcd', 'instructional design', 'assessment'],
        setting: 'A course draft says, "Learners will understand financial ratios," but the assessment asks analysts to interpret quarterly statements.',
        learnerRole: 'You are revising the objective before the assessment blueprint is approved.',
        friction: 'The verb is too vague to guide item writing or workplace performance.',
        decisionPoint: 'How should the objective change?',
        variables: ['Audience', 'Behavior verb', 'Condition', 'Degree of acceptable performance'],
        choices: [
            { label: 'Keep understand', action: 'Leave the wording broad for flexibility.', tradeoff: 'Easy agreement, weak alignment.', feedback: 'Too vague; it does not tell item writers what performance to observe.' },
            { label: 'Use analyze', action: 'Specify that analysts interpret ratios from a quarterly statement and justify a risk claim.', tradeoff: 'More precise, easier to assess.', feedback: 'Best because behavior and condition now match the workplace task.' },
            { label: 'Add content list', action: 'List every ratio covered in the lesson.', tradeoff: 'Clear scope, still weak performance evidence.', feedback: 'Content coverage does not replace observable behavior.' },
        ],
        successCriteria: ['Verb is observable', 'Condition resembles the real task', 'Assessment can directly sample the objective'],
        theoryMoves: ['ABCD makes the performance target inspectable.', 'Bloom level should match the desired cognitive work.', 'Alignment links objective, practice, and assessment evidence.'],
        reflectionPrompt: 'What would a learner have to do for you to believe they met the objective?',
    },
    {
        id: 'truss-snow-load',
        tags: ['statics', 'truss', 'compression', 'snow', 'roof', 'members'],
        setting: 'A gym roof truss must carry an unusually heavy snow load after a late-season storm.',
        learnerRole: 'You are checking which members are likely to be in compression before detailed sizing.',
        friction: 'The drawing looks symmetric, but support reactions and load paths still need to be made explicit.',
        decisionPoint: 'What should be drawn before solving member forces?',
        variables: ['Support reactions', 'Joint load locations', 'Zero-force candidates', 'Compression buckling risk'],
        choices: [
            { label: 'Guess members', action: 'Mark top chords as compression because they are above the roof.', tradeoff: 'Fast intuition, weak proof.', feedback: 'Often plausible but not sufficient; member force signs require equilibrium.' },
            { label: 'FBD first', action: 'Draw the whole-truss free-body diagram and solve reactions.', tradeoff: 'More setup, reliable path.', feedback: 'Best first move because every joint equation depends on the external reactions.' },
            { label: 'Size all larger', action: 'Increase every member size equally.', tradeoff: 'Conservative, inefficient.', feedback: 'May be safe but misses why compression members need buckling attention.' },
        ],
        successCriteria: ['External reactions are solved', 'Member signs come from equilibrium', 'Compression members are checked for buckling'],
        theoryMoves: ['Statics starts with a free-body diagram.', 'The method of joints depends on force balance at each node.', 'Compression capacity is not only material strength; slenderness matters.'],
        reflectionPrompt: 'Which joint would you solve first, and why?',
    },
    {
        id: 'polar-drone-motion',
        tags: ['dynamics', 'polar', 'curvilinear', 'drone', 'velocity', 'acceleration'],
        setting: 'A radar station tracks a rescue drone whose range and bearing both change during a river crossing.',
        learnerRole: 'You are converting the radar data into velocity and acceleration components.',
        friction: 'The radial and transverse directions rotate, so acceleration includes terms that are easy to omit.',
        decisionPoint: 'Which term would most likely reveal a conceptual mistake?',
        variables: ['Range rate', 'Angular rate', 'Angular acceleration', 'Rotating unit vectors'],
        choices: [
            { label: 'Differentiate x-y', action: 'Convert everything to Cartesian coordinates first.', tradeoff: 'Reliable, more algebra.', feedback: 'Valid, but it may hide why polar cross terms appear.' },
            { label: 'Use polar form', action: 'Apply radial and transverse velocity/acceleration equations directly.', tradeoff: 'Efficient, notation-sensitive.', feedback: 'Best when radar gives range and bearing naturally.' },
            { label: 'Ignore cross terms', action: 'Use only second derivatives of range and angle.', tradeoff: 'Looks simple, physically wrong.', feedback: 'This misses centripetal and Coriolis-like contributions from rotating directions.' },
        ],
        successCriteria: ['Velocity has radial and transverse components', 'Acceleration includes rotation-induced terms', 'Units distinguish angular and linear rates'],
        theoryMoves: ['Coordinate choice should match measurement structure.', 'Unit vectors can change even when magnitudes seem simple.', 'Cross terms encode path curvature and changing direction.'],
        reflectionPrompt: 'What physical motion does the 2 r-dot theta-dot term represent?',
    },
    {
        id: 'online-seminar-coi',
        tags: ['online learning', 'community of inquiry', 'moore', 'discussion', 'interaction'],
        setting: 'A 12-week seminar moves online with long lecture recordings and length-graded forum posts.',
        learnerRole: 'You are diagnosing why students comply but report low connection and weak transfer.',
        friction: 'The course has activity, but the activity may not create meaningful learner-content, learner-instructor, or learner-learner interaction.',
        decisionPoint: 'Which interaction should be redesigned first?',
        variables: ['Prompt authenticity', 'Instructor facilitation', 'Peer uptake', 'Cognitive presence evidence'],
        choices: [
            { label: 'More posts', action: 'Require five posts per week instead of three.', tradeoff: 'More volume, more fatigue.', feedback: 'Likely worsens the problem if posts remain length-graded.' },
            { label: 'Case cycles', action: 'Use short cases with peer replies that must revise an initial position.', tradeoff: 'Less volume, more reasoning.', feedback: 'Best because interaction becomes tied to cognitive work.' },
            { label: 'Longer lectures', action: 'Record deeper explanations for each topic.', tradeoff: 'More content, less dialogue.', feedback: 'May improve content access but does not address social or teaching presence.' },
        ],
        successCriteria: ['Learners respond to ideas, not word counts', 'Instructor presence guides reasoning', 'Discussion artifacts show revision or application'],
        theoryMoves: ['Moore separates content, instructor, and learner interaction.', 'Community of Inquiry requires cognitive, social, and teaching presence.', 'Online discussion needs a task structure, not just a posting quota.'],
        reflectionPrompt: 'What evidence would show that a forum reply changed someone’s thinking?',
    },
    {
        id: 'assessment-validity-skew',
        tags: ['assessment', 'validity', 'blueprint', 'objectives', 'instructional design'],
        setting: 'A final exam has 25 items, but 22 target one objective while six other objectives appear once or not at all.',
        learnerRole: 'You are reviewing the assessment before release.',
        friction: 'The pass score looks acceptable, but the test may not represent the intended learning domain.',
        decisionPoint: 'What is the core validity defect?',
        variables: ['Objective weights', 'Item sampling', 'Field performance tasks', 'Score interpretation'],
        choices: [
            { label: 'Raise cut score', action: 'Make passing harder to improve rigor.', tradeoff: 'Higher bar, same sampling flaw.', feedback: 'Rigor does not fix underrepresentation.' },
            { label: 'Reblueprint', action: 'Redistribute items according to objective importance and task frequency.', tradeoff: 'More design work, stronger inference.', feedback: 'Best because validity depends on what the score claims to represent.' },
            { label: 'Add feedback', action: 'Explain missed items after the exam.', tradeoff: 'Better learning support, unchanged evidence quality.', feedback: 'Helpful after testing but does not repair the score interpretation.' },
        ],
        successCriteria: ['Item distribution matches objectives', 'High-priority skills receive enough evidence', 'Score claims match sampled performances'],
        theoryMoves: ['Validity concerns the interpretation of scores.', 'Blueprinting protects against construct underrepresentation.', 'Assessment design should mirror the domain of intended performance.'],
        reflectionPrompt: 'Which objective is currently over-controlling the learner’s score?',
    },
    {
        id: 'ai-critique-log',
        tags: ['ai critique', 'cat100', 'digital citizenship', 'resume', 'revision', 'evidence'],
        setting: 'A learner submits AI-suggested resume edits, but the log only says “accepted” or “rejected.”',
        learnerRole: 'You are deciding the first adaptive support action.',
        friction: 'The artifact shows AI use but not the learner’s judgment about evidence, truthfulness, or role fit.',
        decisionPoint: 'What support would improve the revision evidence fastest?',
        variables: ['Original claim', 'AI suggestion', 'Learner decision', 'Evidence source', 'Disclosure note'],
        choices: [
            { label: 'Praise use', action: 'Reward the learner for using AI efficiently.', tradeoff: 'Encouraging, weak accountability.', feedback: 'Insufficient because digital citizenship requires judgment, not mere tool use.' },
            { label: 'Trace decisions', action: 'Ask for a before/after table with reason and evidence for each accepted edit.', tradeoff: 'More work, clearer authorship.', feedback: 'Best because it makes human judgment visible.' },
            { label: 'Ban AI', action: 'Require a fully manual rewrite.', tradeoff: 'Avoids tool risk, loses critique practice.', feedback: 'Too blunt if the learning goal is responsible AI-supported revision.' },
        ],
        successCriteria: ['Accepted edits are evidence-backed', 'Rejected edits include a reason', 'Disclosure names bounded AI use'],
        theoryMoves: ['Digital citizenship includes transparency and responsibility.', 'Generative learning requires explaining decisions.', 'Artifact evidence should show process, not only final polish.'],
        reflectionPrompt: 'Which accepted AI suggestion most needs evidence before it can stay?',
    },
    {
        id: 'school-policy-memo',
        tags: ['cat531', 'ai policy', 'school', 'privacy', 'equity', 'critical edtech'],
        setting: 'A school policy memo allows any teacher to use AI tools if the output is “educational.”',
        learnerRole: 'You are reviewing the memo before it goes to the principal.',
        friction: 'The policy sounds flexible but leaves privacy, equity, consent, and learning purpose undefined.',
        decisionPoint: 'Which clause needs the most urgent revision?',
        variables: ['Student data boundary', 'Teacher review duty', 'Equity impact', 'Parent notice', 'Learning purpose'],
        choices: [
            { label: 'Keep broad', action: 'Leave decisions to individual teachers.', tradeoff: 'Flexible, inconsistent protection.', feedback: 'Risky because vulnerable students may receive uneven safeguards.' },
            { label: 'Define boundaries', action: 'Specify data, consent, review, and prohibited uses.', tradeoff: 'More restrictive, more defensible.', feedback: 'Best because it turns values into actionable guardrails.' },
            { label: 'List tools', action: 'Approve a fixed set of AI products.', tradeoff: 'Concrete, quickly outdated.', feedback: 'Helpful but incomplete unless paired with use-case rules.' },
        ],
        successCriteria: ['Student data limits are explicit', 'Human review is required for consequential use', 'Equity risks are named before adoption'],
        theoryMoves: ['Critical edtech asks who benefits and who bears risk.', 'Policy should govern practices, not only products.', 'Ethical adoption requires institutional responsibility.'],
        reflectionPrompt: 'What use of AI should the policy clearly forbid?',
    },
    {
        id: 'storyboard-signaling',
        tags: ['storyboard', 'multimedia learning', 'signaling', 'ail606', 'video'],
        setting: 'A storyboard has accurate narration, but every screen uses the same dense diagram with no visual emphasis.',
        learnerRole: 'You are revising the storyboard before production.',
        friction: 'Learners hear the right explanation but cannot tell where to look at each step.',
        decisionPoint: 'What should change in the next storyboard frame?',
        variables: ['Visual focus', 'Narration timing', 'Redundant text', 'Cue placement'],
        choices: [
            { label: 'Highlight path', action: 'Animate or cue only the part being explained.', tradeoff: 'More production planning, clearer attention.', feedback: 'Best because signaling reduces search burden.' },
            { label: 'Add transcript', action: 'Place the full narration on screen.', tradeoff: 'Accessible text, possible redundancy.', feedback: 'Useful as an option, but not as the primary visual solution.' },
            { label: 'Use one diagram', action: 'Keep the same image to avoid distraction.', tradeoff: 'Stable layout, weak guidance.', feedback: 'Stability helps only if the relevant relation is signaled.' },
        ],
        successCriteria: ['Each frame has one visual focus', 'Cue timing matches narration', 'Learners do not need to search the whole diagram'],
        theoryMoves: ['Signaling guides attention to essential material.', 'Temporal contiguity matters when narration and image change together.', 'Reducing search supports germane processing.'],
        reflectionPrompt: 'Where should the learner’s eyes go during the next sentence?',
    },
    {
        id: 'excel-data-story',
        tags: ['excel', 'pivot', 'cat100', 'chart', 'data story', 'claim'],
        setting: 'A pivot-table chart is accurate, but the title says “Results” and the axis label omits units.',
        learnerRole: 'You are giving feedback before the learner presents the data story.',
        friction: 'The chart contains evidence, but the audience cannot quickly infer the claim or measurement context.',
        decisionPoint: 'Which revision will make the chart more defensible?',
        variables: ['Claim-first title', 'Units', 'Source note', 'Comparison group', 'Chart type'],
        choices: [
            { label: 'Style colors', action: 'Make the chart visually brighter.', tradeoff: 'More attractive, same evidence gap.', feedback: 'Not enough; polish cannot replace missing measurement context.' },
            { label: 'Name claim', action: 'Rewrite the title as the finding and add unit/source labels.', tradeoff: 'Less generic, more interpretable.', feedback: 'Best because the audience can read the evidence quickly.' },
            { label: 'Add table', action: 'Place all raw rows under the chart.', tradeoff: 'Transparent, cognitively heavy.', feedback: 'Useful appendix, but the chart itself still needs a clear claim.' },
        ],
        successCriteria: ['Title states the finding', 'Units and source are visible', 'Chart type supports the comparison'],
        theoryMoves: ['Data literacy includes communicating evidence, not only computing it.', 'A chart is an argument with visual evidence.', 'Audience constraints shape the level of detail.'],
        reflectionPrompt: 'What sentence should the chart title let the audience say aloud?',
    },
    {
        id: 'swarm-disaster',
        tags: ['swarm', 'robotics', 'stigmergy', 'disaster', 'bio-inspired'],
        setting: 'A rescue team can deploy one expensive rover or thousands of cheap insect-scale robots into a collapsed building.',
        learnerRole: 'You are choosing the search strategy for the first hour.',
        friction: 'Central control offers precision, while swarm behavior offers coverage and resilience under uncertainty.',
        decisionPoint: 'What evidence would justify a swarm approach?',
        variables: ['Communication loss', 'Search coverage', 'Robot failure rate', 'Signal markers', 'Time pressure'],
        choices: [
            { label: 'One rover', action: 'Send the best robot through the safest path.', tradeoff: 'High sensor quality, single point of failure.', feedback: 'Useful in mapped spaces, fragile in unstable debris.' },
            { label: 'Swarm map', action: 'Use local markers so many small robots build a coverage map.', tradeoff: 'Noisy data, resilient search.', feedback: 'Best when communication and terrain are unpredictable.' },
            { label: 'Wait', action: 'Delay until a human team can enter.', tradeoff: 'Lower robot uncertainty, higher time cost.', feedback: 'May be necessary for safety, but it sacrifices early situational awareness.' },
        ],
        successCriteria: ['Coverage improves despite individual failures', 'Local signals guide collective behavior', 'Human responders receive usable location evidence'],
        theoryMoves: ['Stigmergy coordinates action through environmental traces.', 'Swarm systems trade individual intelligence for collective robustness.', 'Bio-inspired design abstracts a coordination principle.'],
        reflectionPrompt: 'What local signal should each small robot leave behind?',
    },
    {
        id: 'passive-cooling-lab',
        tags: ['passive cooling', 'building', 'termite', 'thermal', 'bio-inspired'],
        setting: 'A desert research building must protect sensitive lab equipment while reducing mechanical cooling demand.',
        learnerRole: 'You are evaluating a passive-cooling concept before the architects commit.',
        friction: 'Passive airflow can reduce energy use, but lab temperatures must stay within tight tolerances.',
        decisionPoint: 'Which prototype evidence matters most?',
        variables: ['Daily temperature swing', 'Vent geometry', 'Equipment heat load', 'Humidity constraint', 'Backup cooling threshold'],
        choices: [
            { label: 'Copy mounds', action: 'Replicate termite mound forms as closely as possible.', tradeoff: 'Biologically faithful, weak site fit.', feedback: 'Resemblance is less important than the airflow and thermal-mass mechanism.' },
            { label: 'Model airflow', action: 'Simulate vent paths and thermal mass under local weather loads.', tradeoff: 'Abstracted, constraint-aware.', feedback: 'Best because it tests the mechanism against lab constraints.' },
            { label: 'Use fans only', action: 'Add more mechanical cooling redundancy.', tradeoff: 'Reliable, energy-intensive.', feedback: 'May be needed as backup but misses the passive design goal.' },
        ],
        successCriteria: ['Temperature stays within equipment tolerance', 'Energy demand is reduced at peak load', 'Backup system triggers are defined'],
        theoryMoves: ['Biomimicry transfers function, not shape alone.', 'Thermal performance depends on context and constraints.', 'Passive systems still need quantitative validation.'],
        reflectionPrompt: 'What would you measure overnight before trusting the passive design?',
    },
    {
        id: 'self-healing-offshore',
        tags: ['self-healing', 'materials', 'offshore', 'resilience', 'maintenance'],
        setting: 'An offshore sensing platform is visited twice a year, and minor panel cracks can grow between inspections.',
        learnerRole: 'You are comparing cheaper composite panels with self-healing polymer panels.',
        friction: 'The expensive material may prevent failures, but only if damage and healing conditions match the site.',
        decisionPoint: 'What evidence should decide the material choice?',
        variables: ['Crack growth rate', 'Salt exposure', 'Repair temperature', 'Inspection interval', 'Failure consequence'],
        choices: [
            { label: 'Choose cheap', action: 'Use lower-cost panels and accept manual inspection.', tradeoff: 'Lower upfront cost, higher hidden risk.', feedback: 'Reasonable only if failure consequences and crack growth are low.' },
            { label: 'Test healing', action: 'Expose damaged samples to site-like salt, temperature, and loading cycles.', tradeoff: 'More validation, better risk estimate.', feedback: 'Best because healing must work under deployment conditions.' },
            { label: 'Overbuild', action: 'Increase panel thickness across the platform.', tradeoff: 'Simple safety margin, added weight.', feedback: 'May help strength but does not address maintenance access.' },
        ],
        successCriteria: ['Healing occurs under site conditions', 'Life-cycle cost includes inspection and failure risk', 'Material choice matches maintenance reality'],
        theoryMoves: ['Resilience is performance after disturbance, not just initial strength.', 'Material selection depends on use environment.', 'Bio-inspired repair mechanisms require deployment-specific evidence.'],
        reflectionPrompt: 'When would the cheaper panel become more expensive over the full life cycle?',
    },
    {
        id: 'eu-ai-workplace',
        tags: ['ai governance', 'eu ai act', 'nist', 'workplace', 'risk'],
        setting: 'A startup wants to sell a workplace performance-prediction system to EU employers.',
        learnerRole: 'You are mapping the governance workflow before market entry.',
        friction: 'The product’s business value depends on predictions that could affect employment opportunities.',
        decisionPoint: 'Which governance frame should be applied first?',
        variables: ['Use context', 'Impact on workers', 'Model transparency', 'Human appeal path', 'Monitoring plan'],
        choices: [
            { label: 'Market first', action: 'Launch with a disclaimer that managers make final decisions.', tradeoff: 'Fast entry, weak protection.', feedback: 'A disclaimer does not remove high-risk employment implications.' },
            { label: 'Risk classify', action: 'Classify the use case, document risks, and design oversight before deployment.', tradeoff: 'Slower, regulator-ready.', feedback: 'Best because obligations follow the use context and potential harm.' },
            { label: 'Explain model', action: 'Publish a model card only.', tradeoff: 'Improves transparency, incomplete governance.', feedback: 'Useful artifact, but it does not cover monitoring, appeal, and impact controls.' },
        ],
        successCriteria: ['Risk tier is justified by use', 'Human oversight has real authority', 'Monitoring catches disparate or harmful outcomes'],
        theoryMoves: ['AI governance starts from sociotechnical use, not model type alone.', 'Risk management requires controls across the life cycle.', 'Transparency is necessary but not sufficient.'],
        reflectionPrompt: 'Who could be harmed if the prediction is wrong, and what remedy would they have?',
    },
    {
        id: 'privacy-deidentified',
        tags: ['privacy', 'hipaa', 'gdpr', 'de-identified', 'health', 'ai ethics'],
        setting: 'A health-system vendor wants to share de-identified patient data containing diagnoses, dates, and zip codes.',
        learnerRole: 'You are reviewing whether the AI training proposal is privacy-defensible.',
        friction: 'The dataset removes names but still contains quasi-identifiers that may enable linkage.',
        decisionPoint: 'What should the review require before sharing?',
        variables: ['Re-identification risk', 'Data minimization', 'Purpose limitation', 'Access controls', 'Retention period'],
        choices: [
            { label: 'Share as is', action: 'Treat de-identification as complete protection.', tradeoff: 'Simple transfer, high linkage risk.', feedback: 'Weak because quasi-identifiers can still expose patients.' },
            { label: 'Minimize', action: 'Remove or generalize fields, document purpose, and restrict access.', tradeoff: 'Less granular data, stronger privacy posture.', feedback: 'Best because risk is reduced before governance promises are made.' },
            { label: 'Ask consent later', action: 'Share now and update notices after training starts.', tradeoff: 'Fast, ethically backward.', feedback: 'Consent and notice cannot be retrofitted after sensitive use begins.' },
        ],
        successCriteria: ['Only necessary fields remain', 'Linkage risk is assessed', 'Use limits and retention are enforceable'],
        theoryMoves: ['Privacy risk remains after direct identifiers are removed.', 'Data minimization reduces harm before access controls are tested.', 'Legal compliance and ethical defensibility both depend on purpose and necessity.'],
        reflectionPrompt: 'Which field would you generalize first to reduce linkage risk?',
    },
    {
        id: 'capstone-defense-evidence',
        tags: ['capstone', 'evidence board', 'limitations', 'transfer', 'ail606'],
        setting: 'A capstone defense claims the prototype is ready for transfer, but the evidence board lists only positive pilot comments.',
        learnerRole: 'You are preparing the learner for a stronger defense.',
        friction: 'The claim is optimistic, but limitations and boundary conditions are missing.',
        decisionPoint: 'What evidence should be added before transfer is claimed?',
        variables: ['Pilot sample', 'Observed failures', 'Context boundary', 'Revision trace', 'Transfer claim'],
        choices: [
            { label: 'Add praise', action: 'Include more favorable quotes from pilot users.', tradeoff: 'Persuasive tone, weak warrant.', feedback: 'Positive comments do not establish transfer readiness.' },
            { label: 'Name limits', action: 'Add failure cases, constraints, and revisions tied to evidence.', tradeoff: 'Less polished, more credible.', feedback: 'Best because defensible transfer includes boundaries.' },
            { label: 'Claim broadly', action: 'State that the design applies to all similar courses.', tradeoff: 'Ambitious, unsupported.', feedback: 'Too strong without evidence from varied contexts.' },
        ],
        successCriteria: ['Limitations are explicit', 'Revision decisions cite evidence', 'Transfer claims name where the design should and should not work'],
        theoryMoves: ['Design knowledge becomes stronger when boundaries are visible.', 'Evidence boards should show reasoning, not only outcomes.', 'Transfer depends on similarity between contexts.'],
        reflectionPrompt: 'What limitation would make the defense more credible rather than weaker?',
    },
    {
        id: 'github-pages-accessibility',
        tags: ['github pages', 'accessibility', 'privacy', 'cat100', 'portfolio'],
        setting: 'A learner publishes a GitHub Pages portfolio with a clear layout but no alt text and a public resume PDF.',
        learnerRole: 'You are giving the first revision instruction.',
        friction: 'Publishing works technically, but accessibility and privacy checks are incomplete.',
        decisionPoint: 'Which revision should happen before final submission?',
        variables: ['Alt text', 'Personal data exposure', 'Navigation labels', 'Repository visibility', 'Mobile view'],
        choices: [
            { label: 'Celebrate launch', action: 'Mark complete because the site is live.', tradeoff: 'Recognizes progress, misses citizenship goals.', feedback: 'Publishing alone is not enough for digital citizenship.' },
            { label: 'Run checklist', action: 'Require accessibility and privacy fixes before polish.', tradeoff: 'Less glamorous, safer publication.', feedback: 'Best because public work must be usable and appropriately bounded.' },
            { label: 'Change theme', action: 'Make the portfolio visually more impressive.', tradeoff: 'Better style, unchanged risk.', feedback: 'Aesthetic revision should follow access and privacy basics.' },
        ],
        successCriteria: ['Images have meaningful alt text', 'Private information is removed or intentionally bounded', 'Navigation works on mobile and keyboard'],
        theoryMoves: ['Digital citizenship includes responsible publication.', 'Accessibility is part of audience-aware communication.', 'Technical completion does not equal ethical readiness.'],
        reflectionPrompt: 'What information should not be public on this portfolio?',
    },
    {
        id: 'leadership-training-roi',
        tags: ['evaluation', 'roi', 'training', 'kirkpatrick', 'analytics'],
        setting: 'A CFO asks whether a leadership program caused better retention, but staffing changed during the same quarter.',
        learnerRole: 'You are planning the evaluation evidence.',
        friction: 'The business metric improved, but the design does not yet separate training effects from other changes.',
        decisionPoint: 'What evidence would make the ROI claim less fragile?',
        variables: ['Baseline trend', 'Comparison group', 'Implementation fidelity', 'Retention timing', 'Cost assumptions'],
        choices: [
            { label: 'Report gain', action: 'Attribute the retention increase to training.', tradeoff: 'Simple story, weak causality.', feedback: 'Too strong because competing explanations remain.' },
            { label: 'Compare groups', action: 'Use matched teams or a staged rollout to compare change over time.', tradeoff: 'More analysis, stronger inference.', feedback: 'Best because it addresses alternative explanations.' },
            { label: 'Survey smiles', action: 'Use participant satisfaction as the main evidence.', tradeoff: 'Easy data, low business validity.', feedback: 'Reactions cannot prove behavior or organizational outcomes.' },
        ],
        successCriteria: ['Comparison logic is explicit', 'Costs and benefits are bounded', 'Alternative explanations are addressed'],
        theoryMoves: ['Evaluation claims should match the strength of the design.', 'ROI requires credible outcome attribution and cost logic.', 'Reaction data is not enough for performance impact.'],
        reflectionPrompt: 'What non-training change could explain the same retention pattern?',
    },
    {
        id: 'robotic-knee-torque',
        tags: ['dynamics', 'torque', 'moment arm', 'knee', 'biomechanics'],
        setting: 'A powered knee brace helps users stand, but the motor overheats during repeated chair-rise trials.',
        learnerRole: 'You are choosing whether to increase motor force or change the actuator moment arm.',
        friction: 'Both choices affect torque, but they change weight, heat, range of motion, and user comfort differently.',
        decisionPoint: 'Which design variable should be tested first?',
        variables: ['Moment arm length', 'Motor force', 'Joint angle', 'Thermal limit', 'User comfort'],
        choices: [
            { label: 'More force', action: 'Use a stronger motor at the same geometry.', tradeoff: 'Direct torque increase, more heat and weight.', feedback: 'May solve peak torque but worsens the overheating constraint.' },
            { label: 'Change arm', action: 'Increase effective moment arm within motion constraints.', tradeoff: 'Better leverage, geometry tradeoffs.', feedback: 'Best first comparison because torque can rise without simply adding motor load.' },
            { label: 'Slow motion', action: 'Reduce assistance speed.', tradeoff: 'Lower power demand, weaker user experience.', feedback: 'Useful fallback but may not meet functional support needs.' },
        ],
        successCriteria: ['Torque target is met across joint angles', 'Thermal load stays within limits', 'Brace remains comfortable and wearable'],
        theoryMoves: ['Torque depends on force and perpendicular distance.', 'Design variables interact with human constraints.', 'A good dynamics model informs tradeoffs, not just calculations.'],
        reflectionPrompt: 'At which knee angle does the moment arm matter most?',
    },
]

function normalize(value) {
    return String(value || '').toLowerCase()
}

function hashString(value) {
    return normalize(value).split('').reduce((hash, char) => ((hash << 5) - hash + char.charCodeAt(0)) | 0, 0)
}

function selectVisual(seed) {
    return VISUALS[Math.abs(hashString(seed)) % VISUALS.length]
}

export function pickScenario({ topic, context, course, variant = 0 }) {
    const source = `${topic} ${context} ${course}`
    const terms = normalize(source).split(/[^a-z0-9@]+/).filter(Boolean)
    const scored = SCENARIOS.map((scenario) => {
        const score = scenario.tags.reduce((sum, tag) => {
            const normalizedTag = normalize(tag)
            return sum + (normalize(source).includes(normalizedTag) || terms.some((term) => normalizedTag.includes(term) || term.includes(normalizedTag)) ? 1 : 0)
        }, 0)
        return { scenario, score }
    }).sort((left, right) => {
        if (right.score !== left.score) return right.score - left.score
        return Math.abs(hashString(`${source}:${left.scenario.id}`)) - Math.abs(hashString(`${source}:${right.scenario.id}`))
    })

    const pool = scored.filter((item) => item.score === scored[0]?.score).map((item) => item.scenario)
    const fallbackPool = pool.length > 0 ? pool : SCENARIOS
    const index = Math.abs(hashString(`${source}:${variant}`)) % fallbackPool.length
    const scenario = fallbackPool[index]

    return {
        ...scenario,
        visual: selectVisual(`${scenario.id}:${source}:${variant}`),
        source: 'curated'
    }
}

